### ISSUE TITLE
Swift Playgrounds on iPad: The target type, “ClangTarget”, is not supported

### ISSUE THREAD

**Issue by oxygen** [JimmyMAndersson/StatKit#127]
Any idea why there’s incompatibility with Swift Playgrounds on iPad?

Just a simple `import StatKit` throws “ “The target type, “ClangTarget”, is not supported”.

It seems widespread, I’m guessing it has something to do with the project configuration?
https://www.hackingwithswift.com/forums/swift/some-packages-don-t-load-in-swift-playgrounds-4/12328

**Comment by JimmyMAndersson** [comment]
Hi @oxygen!

The latest release of StatKit has a dependency on the Swift Numerics package, which is not a pure Swift dependency (_NumericsShims is a C target). Swift Playgrounds does not currently support targets that are not pure Swift, and unfortunately, I don't know if that will change in the future.

However, if you just want to toy around with StatKit and don't care too much about getting all the very latest bells and whistles, StatKit beta 4 does not depend on Numerics and should be okay to run on the iPad.

**Comment by oxygen** [comment]
Thanks
